# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19cb5db88522965fd2720069c964eb0658cddc48c24a24f66d6aa69ca0cd2ce2346ab68c6668fab4547fbd154c99a8c89e02fe06966df748c50728bd8170efa5

test:
  secret_key_base: f2f8a3371dfaa116ff887fb521fea0215b32612b280556fbd611913e210ce1701ad99df781889ea32f35138aa9e9b2455a848393dc1d66d904eeb0c23d2869ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
